# Device communication protocol parameters
http:
  request_timeout: 60000
# MQTT server parameters
mqtt:
  # Enable/disable mqtt transport protocol.
  enabled: true
  bind_address: 0.0.0.0
  bind_port: 1883
  adaptor: JsonMqttAdaptor
  timeout: 10000
  netty:
    leak_detector_level: DISABLED
    boss_group_thread_count: 1
    worker_group_thread_count: 8
    max_payload_size: 65536
  ssl:
    # Enable/disable SSL support
    enabled: false
    # SSL protocol: See http://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SSLContext
    protocol: TLSv1.2
    # Path to the key store that holds the SSL certificate
    key_store: mqttserver.jks
    # Password used to access the key
    key_store_password: server_ks_password
    # Password used to access the key
    key_password: server_key_password
    # Type of the key store
    key_store_type: JKS

# CoAP server parameters
coap:
  # Enable/disable coap transport protocol.
  enabled: false
  bind_address: 0.0.0.0
  bind_port: 5683
  adaptor: JsonCoapAdaptor
  timeout: 10000

database:
  type: sql # sql OR mongodb

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/groza?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: james
